steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fastapi-secrets-api:latest', '.']
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fastapi-secrets-api:latest']
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fastapi-secrets-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/fastapi-secrets-api:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'OPENAI_API_KEY=${_OPENAI_API_KEY},CALENDAR_API_TOKEN=${_CALENDAR_API_TOKEN}'
    timeout: '1200s'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/fastapi-secrets-api:latest'

# Substitution variables (can be set in Cloud Build trigger)
substitutions:
  _OPENAI_API_KEY: 'asdasdqw3234324'
  _CALENDAR_API_TOKEN: 'dfdsfe232324'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY


